BusinessEntities/PMS_MVC/Controllers/Admin/UserGroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessEntities; 
using System.IO;
using System.Drawing; 

namespace PMS_MVC.Controllers.Admin
{
    public class UserGroupController : Controller
    {
       /// <summary>
       /// declare WCF service object
       /// </summary>
        WcfGetService.Getservice _OBJService = new WcfGetService.Getservice();
        #region "User Group"
        /// <summary>
        /// Get all values from UserGroup
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewUserGroup()
        {
            ViewBag.UserGroup = _OBJService.GetAllUserGroup();
            return View();
        }

        /// <summary>
        /// Get UserGroup based on the search text typed
        /// </summary>
        /// <param name="F_USERGROUP_NAME"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SearchUserGroup(string UserGroupName)
        {
            ViewBag.UserGroup = _OBJService.GetAllUserGroup().Where(m => m.UserGroupName.ToLower().Contains(UserGroupName.ToLower())).ToList();
             return View("ViewUserGroup"); 
        }

       /// <summary>
       /// Get UserGroup Based on the Grid Edit click
       /// </summary>
       /// <param name="UserGroupID"></param>
       /// <returns></returns>
        [OutputCache(Duration = 0)]
        [HttpGet]
        public ViewResult CRUDUserGroup(Guid UserGroupID)
        {
            if (UserGroupID != Guid.Empty)
            {
                UserGroupEntities UserGroup_Entity = _OBJService.GetAllUserGroup().Where(m => m.UserGroupId == UserGroupID).FirstOrDefault();
                return View(UserGroup_Entity); 
            }
            else
            {
                ViewBag.UserGroup = new SelectList(_OBJService.GetAllUserGroup(), "UserGroupId", "UserGroupName");
                var UserGroup = _OBJService.GetAllUserGroup().Where(m => m.UserGroupId == UserGroupID).FirstOrDefault();
                return View(UserGroup);
            }
        }
        /// <summary>
        /// CRUD ERROR MSG DISPLAY
        /// </summary>
        /// <returns></returns>
        public ActionResult CRUDUserGroup()
        {
            return View();
        }
        /// <summary>
        /// CRUD User Group based on the primary key value
        /// Method calls stored Procedure
        /// </summary>
        /// <param name="UserGroup_Entity"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CRUDUserGroup(UserGroupEntities UserGroup_Entity)
        {
            try
            {
                var result = 0;
                if (ModelState.IsValid)
                { 
                    if (UserGroup_Entity.UserGroupId != Guid.Empty)
                    {
                        result = _OBJService.InsertUpdateUserGroup(UserGroup_Entity);
                        if (result == 1)
                        {   
                            ViewBag.SuccessMessage = "Updated successfully";
                           
                        }
                    }
                    else
                    {
                        UserGroup_Entity.UserGroupId = Guid.NewGuid();
                        result = _OBJService.InsertUpdateUserGroup(UserGroup_Entity);
                        {
                            ViewBag.SuccessMessage = "Updated successfully";
                          
                        }
                    }
                }
                else
                {
                    if (result == 0)
                        ViewBag.SuccessMessage = "Error : Try After sometime";

                    ViewBag.UserGroup = new SelectList(_OBJService.GetAllUserGroup(), "UserGroupId", "UserGroupName");
                    return View("CRUDUserGroup");
                }
                return View("CRUDUserGroup");
                //return RedirectToAction("ViewUserGroup");
            }

            catch (Exception ex)
            {
                ViewBag.SuccessMessage = ex.Message;
                return View("CRUDUserGroup");
            }
        }
        #endregion

        #region  "User Type"
        /// <summary>
        /// display all user Type
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewUserType()
        {
            ViewBag.UserType = _OBJService.GetAllUserType();
            return View();
        }
        /// <summary>
        /// Search User Type Based on User type
        /// </summary>
        /// <param name="UserTypeName"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SearchUserType(string UserTypeName)
        {
            ViewBag.UserType = _OBJService.GetAllUserType().Where(m => m.UserTypeName.ToLower().Contains(UserTypeName.ToLower())).ToList();
            return View("ViewUserType");
        }
        /// <summary>
        /// Filter user type base on usertypeid
        /// </summary>
        /// <param name="UserTypeId"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CRUDUserType(Guid UserTypeId)
        {
            UserTypeEntities UserType_Entity = new UserTypeEntities(); 
            if (Request.IsAjaxRequest())
            {
                if (UserTypeId != Guid.Empty)
                {
                    UserType_Entity = _OBJService.GetAllUserType().Where(m => m.UserTypeId == UserTypeId).FirstOrDefault();
                    ViewBag.UserType = UserType_Entity;
                }
                else
                {
                    ViewBag.UserType = new SelectList(_OBJService.GetAllUserType(), "UserTypeId", "UserTypeName");
                    UserType_Entity = _OBJService.GetAllUserType().Where(m => m.UserTypeId == UserTypeId).FirstOrDefault();
                }
                return PartialView(UserType_Entity);
            }
            else
                return View(UserType_Entity);
        }
        /// <summary>
        /// update the user Type based on the Entity value
        /// </summary>
        /// <param name="UserType_Entity"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CRUDUserType(UserTypeEntities UserType_Entity)
        {
            try 
            {
                var result = 0;
                if (ModelState.IsValid)
                {
                    if (UserType_Entity.UserTypeId != Guid.Empty)
                    {
                        result = _OBJService.InsertUpdateUserType(UserType_Entity);
                        if (result == 1)
                        {
                            TempData["Msg"] = "Data updated Successfully";
                            ModelState.Clear();
                        }
                    }
                    else
                    {
                        result = _OBJService.InsertUpdateUserType(UserType_Entity);
                        if (result == 1)
                        {
                            TempData["Msg"] = "Data saved Successfully";
                            ModelState.Clear();
                        }
                    }
                    return RedirectToAction("ViewUserType");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex) { throw ex; }

        }

        #endregion

        #region "User"
        /// <summary>
        /// View all users
        /// </summary>
        /// <returns></returns>
        public ActionResult ViewUser()
        {
            ViewBag.User = _OBJService.GetAllUsers();
            return View();
        }
        /// <summary>
        /// Search User Based on Username
        /// </summary>
        /// <param name="Username"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult SearchUsers(string Username)
        {
            ViewBag.User  = _OBJService.GetAllUsers().Where(m => m.Username.ToLower().Contains(Username.ToLower()) || m.EmailAddress.ToLower().Contains(Username.ToLower()) ).ToList();
            return View("ViewUser");
        }
        /// <summary>
        /// Filter user base on userid , Assigning Image value in the Avatar
        /// </summary>
        /// <param name="Userid"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CRUDUsers(Guid Userid)
        {
            UserEntities User_Entity = new UserEntities();
            if (Request.IsAjaxRequest())
            {
                if (Userid != Guid.Empty)
                {
                    BindDropDownList_CRUDUsers();
                    User_Entity =_OBJService.GetAllUsers().Where(m=>m.UserId == Userid).FirstOrDefault();
                    ViewBag.Avatar = User_Entity.Avatar;
                    User_Entity.Avatar = string.Format("data:image/gif;base64,{0}", ViewBag.Avatar);
                    ViewBag.User = User_Entity;
                }
                else
                {
                    BindDropDownList_CRUDUsers();
                    User_Entity = _OBJService.GetAllUsers().Where(m => m.UserId == Userid).FirstOrDefault();
                    ViewBag.Avatar = null;
                    
                }
                return PartialView(User_Entity);
            }
            else
                return View(User_Entity);
        }
        /// <summary>
        ///  update the user based on the Entity value
        /// </summary>
        /// <param name="User_Entity"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CRUDUsers(UserEntities User_Entity)
        {

            try
            {
                var result = 0;
                if (User_Entity.UserGroupEntity.UserGroupId != Guid.Empty)
                {

BusinessEntities/PMS_MVC/Views/UserGroup/CRUDUserGroup.cshtml
@model BusinessEntities.UserGroupEntities
@{
    ViewBag.Title = "CRUDUserGroup";
}
<h1>
    View/Edit User Group</h1>
<div class="form-block">
    @{
        <div>
            @if (!String.IsNullOrEmpty(ViewBag.SuccessMessage))
            {
                <div id="dialog-confirm" style="display: none">
                    <p>
                        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
                        @ViewBag.SuccessMessage
                    </p>
                </div>
                <script>
                    $(function () {
                        $("#dialog-confirm").dialog({ height:100,model: true });
                    });
                </script>
            }
        </div> 
    }

    @using (Html.BeginForm())
    { 
        <fieldset> 
        <div class="fleft" style="width:100%">
            <div class="row">
                <label>
                    User Group
                </label>
                @Html.HiddenFor(m => m.UserGroupId) 
                @Html.EditorFor(m => m.UserGroupName)  
                @Html.ValidationMessageFor(m => m.UserGroupName)  
                <div class="clear">
                </div>
            </div>
            <div class="row">
                <label>
                    Status</label>
                @Html.CheckBoxFor(m => m.Active)
                <div class="clear">
                </div>
            </div>
            <div class="row">
                <input type="submit" value="Save" />
                @Html.ActionLink("Back to List", "ViewUserGroup")
                <div class="clear">
                </div>
            </div>
        </div>
        </fieldset> 
    }
</div>

BusinessEntities/PMS_MVC/Views/UserGroup/CRUDUserType.cshtml
@model BusinessEntities.UserTypeEntities
@{
    ViewBag.Title = "CRUDUserType";
}
 
<div class="form-block">
    @{
        <div>
            @if (!String.IsNullOrEmpty(ViewBag.SuccessMessage))
            {
                <div id="dialog-confirm" style="display: none">
                    <p>
                        <span class="ui-icon ui-icon-alert" style="float: left; margin: 0 7px 20px 0;"></span>
                        @ViewBag.SuccessMessage
                    </p>
                </div>
                <script>
                    $(function () {
                        $("#dialog-confirm").dialog({ height: 100, model: true });
                    });
                </script>
            }
        </div> 
    }

    @using (Html.BeginForm())
    { 
        <fieldset>
     
        <div class="fleft" style="width:100%">
            <div class="row">
                <label>
                    User Type
                </label>
                @Html.HiddenFor(m => m.UserTypeId) 
                @Html.EditorFor(m => m.UserTypeName)  
                @Html.ValidationMessageFor(m => m.UserTypeName, "*")  
                <div class="clear">
                </div>
            </div>
            <div class="row">
                <label>
                    Status</label>
                @Html.CheckBoxFor(m => m.Active)
                <div class="clear">
                </div>
            </div>
            <div class="row">
                <input type="submit" value="Save" />
                @Html.ActionLink("Back to List", "ViewUserType")
                <div class="clear">
                </div>
            </div>
        </div>
        </fieldset> 
    }
</div>

BusinessEntities/PMS_MVC/Views/UserGroup/ViewUser.cshtml
@model BusinessEntities.UserEntities
@{
    ViewBag.Title = "ViewUsers";
}
<h1>
    User</h1>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.pager.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("table.tablesorter").tablesorter({ widthFixed: true, sortList: [[0, 0]] })
            .tablesorterPager({ container: $("#pager"), size: $(".pagesize option:selected").val() });
    });

    $(document).ready(function () {
        $(".editDialog").live("click", function (e) { // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-edit").dialog({
                title: 'Edit',
                autoOpen: false,
                resizable: false,
                height: 685,
                width: 1150,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);
                }, close: function (event, ui) {
                    $(this).dialog('close');
                }
            });
            $("#dialog-edit").dialog('open');
            return false;
        });
        $(".CreateDialog").live("click", function (e) { // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-edit").dialog({
                title: 'Create',
                autoOpen: false,
                resizable: false,
                height: 685,
                width: 1150,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);
                }, close: function (event, ui) {
                    $(this).dialog('close');
                }
            });
            $("#dialog-edit").dialog('open');
            return false;
        });
    });
    
</script>
<div class="alert-box">
    @TempData["Msg"]
</div>
<div class="Gridstyle">
    <div class="search-style">
        @using (Html.BeginForm("SearchUsers", "UserGroup", FormMethod.Get))
        { 
            <h2>
                <text>Search User</text>
            </h2>
            @Html.EditorFor(m => m.Username)
            <input type="submit" value="Search" style="margin-left: 5px;" />
            
            @Html.ActionLink("Create", "CRUDUsers", new { UserId = Guid.Empty }, new { @class = "CreateDialog" })
        }
    </div>
    <div class="clear">
    </div>
    <table class="tablesorter" style="WIDTH:80%">
        <thead>
            <tr>
                <th>
                    Employee Id
                </th>
                <th>
                    User Name
                </th>
                <th>
                    Email Address
                </th>
                <th>
                    DOJ
                </th>
                <th>
                    Designation
                </th>
                <th>
                    User Group
                </th>
                <th>
                    Blood Group
                </th>
                <th>
                    Status
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var p in ViewBag.User)
                {
                <tr>
                    <td>
                        @p.EmployeeId
                    </td>
                    <td>
                        @p.Username
                    </td>
                    <td>
                        @p.EmailAddress
                    </td>
                    <td>
                        @p.DOJ
                    </td>
                      <td>
                        @p.DesignationEntity.EmployeeDesigName
                    </td>
                    <td>
                        @p.UserGroupEntity.UserGroupName
                    </td>
                      <td>
                        @p.BloodGroupEntity.BloodGroupName
                    </td> 
                    <td>
                        @if (@p.Active == false)
                        {
                            @:InActive
                        }
                        @if (@p.Active == true)
                        {
                            @:Active
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "CRUDUsers", "UserGroup", new { UserId = @p.UserId }, new { @class = "editDialog" })
                    </td>
                </tr>
                }
            }
        </tbody>
    </table>
    <div id="pager">
        <input type="text" class="pagedisplay" />
        <select class="pagesize">
            <option value="5">5</option>
            <option selected="selected" value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
        <img src="@Url.Content("~/Content/img/first.png")" class="first" />
        <img src="@Url.Content("~/Content/img/prev.png")" class="prev" />
        <img src="@Url.Content("~/Content/img/next.png")" class="next" />
        <img src="@Url.Content("~/Content/img/last.png")" class="last" />
    </div>
</div>
<div id="dialog-edit" style="display: none">
</div>

BusinessEntities/PMS_MVC/Views/UserGroup/ViewUserGroup.cshtml
@model BusinessEntities.UserGroupEntities
@{
    ViewBag.Title = "ViewUserGroup";
}
<h1>
    User Group</h1>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.pager.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("table.tablesorter").tablesorter({ widthFixed: true, sortList: [[0, 0]] })
            .tablesorterPager({ container: $("#pager"), size: $(".pagesize option:selected").val() });
    });
</script>
<div class="Gridstyle">
    <div class="search-style">
        @using (Html.BeginForm("SearchUserGroup", "UserGroup", FormMethod.Get))
        { 
            <h2>
                <text>Search User Group</text>
            </h2>
            @Html.EditorFor(m => m.UserGroupName)
            <input type="submit" value="Search" style="margin-left:5px;"/>
            
             @Html.ActionLink("Create", "CRUDUserGroup", new { UserGroupID = Guid.Empty })
            
        }
    </div>
    <div class="clear">
    </div>
    <table class="tablesorter">
        <thead>
            <tr>
                <th>
                    User Group
                </th>
                <th>
                    Status
                </th>
                <th>
                     
                </th> 
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var p in ViewBag.UserGroup)
                {
                <tr>
                    <td>
                        @p.UserGroupName
                    </td>
                    <td>
                        @if (@p.Active == false)
                        {
                            @:InActive
                                            }
                        @if (@p.Active == true)
                        {
                            @:Active
                                            }
                    </td>
                     <td>
                     
                            @Html.ActionLink("Edit", "CRUDUserGroup", new { UserGroupID = @p.UserGroupId })
                        </td>
                    
                </tr>
                }
            }
        </tbody>
    </table>
    <div id="pager">
        <input type="text" class="pagedisplay" />
        <select class="pagesize">
            <option selected="selected" value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
        <img src="@Url.Content("~/Content/img/first.png")" class="first" />
        <img src="@Url.Content("~/Content/img/prev.png")" class="prev" />
        <img src="@Url.Content("~/Content/img/next.png")" class="next" />
        <img src="@Url.Content("~/Content/img/last.png")" class="last" />
    </div>
</div>

BusinessEntities/PMS_MVC/Views/UserGroup/ViewUserType.cshtml
@model BusinessEntities.UserTypeEntities
@{
    ViewBag.Title = "ViewUserType";
}
<h1>
    User Type</h1>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tablesorter.pager.js")" type="text/javascript"></script>
<script type="text/javascript">
    $(function () {
        $("table.tablesorter").tablesorter({ widthFixed: true, sortList: [[0, 0]] })
            .tablesorterPager({ container: $("#pager"), size: $(".pagesize option:selected").val() });
    });

    $(document).ready(function () {
        $(".editDialog").live("click", function (e) { // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-edit").dialog({
                title: 'Edit',
                autoOpen: false,
                resizable: false,
                height: 455,
                width: 600,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);
                }, close: function (event, ui) {
                    $(this).dialog('close');
                }
            });
            $("#dialog-edit").dialog('open');
            return false;
        });
        $(".CreateDialog").live("click", function (e) { // e.preventDefault(); use this or return false
            var url = $(this).attr('href');
            $("#dialog-edit").dialog({
                title: 'Create',
                autoOpen: false,
                resizable: false,
                height: 455,
                width: 600,
                show: { effect: 'drop', direction: "up" },
                modal: true,
                draggable: true,
                open: function (event, ui) {
                    $(this).load(url);
                }, close: function (event, ui) {
                    $(this).dialog('close');
                }
            });
            $("#dialog-edit").dialog('open');
            return false;
        });
    });
    
</script>  
     <div class="alert-box">
     @TempData["Msg"] 
     </div>
<div class="Gridstyle">
    <div class="search-style">
        @using (Html.BeginForm("SearchUserType", "UserGroup", FormMethod.Get))
        { 
            <h2>
                <text>Search User Type</text>
            </h2>
            @Html.EditorFor(m => m.UserTypeName)
            <input type="submit" value="Search" style="margin-left: 5px;" />
            
            @Html.ActionLink("Create", "CRUDUserType", new { UserTypeID = Guid.Empty }, new { @class = "CreateDialog" })
        }
    </div>
    <div class="clear">
    </div>
    <table class="tablesorter">
        <thead>
            <tr>
                <th>
                    User Type
                </th>
                <th>
                    Status
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @{
                foreach (var p in ViewBag.UserType)
                {
                <tr>
                    <td>
                        @p.UserTypeName
                    </td>
                    <td>
                        @if (@p.Active == false)
                        {
                            @:InActive
                        }
                        @if (@p.Active == true)
                        {
                            @:Active
                        }
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "CRUDUserType", "UserGroup", new { UserTypeId = @p.UserTypeId }, new { @class = "editDialog" })
                    </td>
                </tr>
                }
            }
        </tbody>
    </table>
    <div id="pager">
        <input type="text" class="pagedisplay" />
        <select class="pagesize">
            <option selected="selected" value="5">5</option>
            <option value="10">10</option>
            <option value="20">20</option>
            <option value="30">30</option>
            <option value="40">40</option>
        </select>
        <img src="@Url.Content("~/Content/img/first.png")" class="first" />
        <img src="@Url.Content("~/Content/img/prev.png")" class="prev" />
        <img src="@Url.Content("~/Content/img/next.png")" class="next" />
        <img src="@Url.Content("~/Content/img/last.png")" class="last" />
    </div>
</div>
<div id="dialog-edit" style="display: none">
</div> 